# Generated by Django 4.2.17 on 2024-12-15 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManApp', '0006_alter_file_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='manager_id',
        ),
        migrations.AlterField(
            model_name='file',
            name='share_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
